services:
  image-compress:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MAX_IMAGE_SIZE=67108864  # 64MB para producci칩n
      - MAX_BATCH_SIZE=20        # M치s im치genes en lote para producci칩n
      - LOG_LEVEL=warn
      - SWAGGER_HOST=your-domain.com
      - SWAGGER_SCHEME=https
      - DEFAULT_QUALITY=85
      - DEFAULT_FORMAT=jpeg
      - REQUEST_TIMEOUT=120
      - UPLOAD_TIMEOUT=600
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

